apiVersion: v1
kind: Pod
metadata:
    name: grafana-pod
    labels:
      name: grafana-pod
      app: demo-car-app
spec:
  containers:
    - name: demo-car-app
      image: grafana/grafana:latest
      ports:
        - containerPort: 3000