apiVersion: v1
kind: Service
metadata:
    name: influx-service
    labels:
      name: influx-service
      app: demo-car-app
spec:
#  type: NodePort
  ports:
    - port: 8086
      targetPort: 8086
#      NodePort: 30005
  selector:
      name: influx-pod
      app: demo-car-app