apiVersion: v1
kind: Pod
metadata:
    name: influx-pod
    labels:
      name: influx-pod
      app: demo-car-app
spec:
  containers:
    - name: demo-car-app
      image: influxdb:1.8
      ports:
        - containerPort: 8086