apiVersion: v1
kind: Pod
metadata:
    name: k6-pod
    labels:
      name: k6-pod
      app: demo-car-app
spec:
  containers:
    - name: demo-car-app
      image: loadimpact/k6:latest
      ports:
        - containerPort: 6565