apiVersion: v1
kind: Service
metadata:
    name: k6-service
    labels:
      name: k6-service
      app: demo-car-app
spec:
#  type: NodePort
  ports:
    - port: 6565
      targetPort: 6565
#      NodePort: 30005
  selector:
      name: k6-pod
      app: demo-car-app